### ISSUE TITLE
nvme and mmcblk installation fails

### ISSUE THREAD

**Issue by VVSShh** [dzacca/zfs_on_root#2]
Cool script, congrats!
I suspect wrong grep clause in /etc/fstab generation for new system - ZBM_install() routine. If disk name ends with a digit, like 'nvme0n1', ''mmcblk1n1' or similar, 'p' is added to partition before the partition number - 'nvme0n1p1', etc.
I suggest replace **grep "${DISK}${BOOT_PART}"** with something like **grep -E "^/dev/${DISK}(p)?${BOOT_PART}"**, or similar.

**Comment by dzacca** [comment]
Would you be so kind to send the output of "ls -la /dev/disk/by-id" taken from a machine with nvme or mmcblk and with one of those disks with one or two partitions created, please?
I don't have any at hand at the moment

**Comment by dzacca** [comment]
I see, thank you for raising this. I have an nvme machine at hand, will test what changes are needed

**Comment by dzacca** [comment]
This is fixed now. Thank you for the head-up

**Comment by dzacca** [comment]
done

**Comment by dzacca** [comment]
fixed as per VVShh recommendation
